const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const csv = require('csv-parse/sync');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceRoleKey) {
  console.error('Missing Supabase environment variables');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);
const csvPath = '/Users/leopura/Desktop/II Membership/II Members_ST.csv';

async function importCSV() {
  try {
    console.log('📂 Reading CSV file...');
    const fileContent = fs.readFileSync(csvPath, 'utf-8');
    
    // Split by lines and skip first line ("II MEMBERSHIP LIST")
    const lines = fileContent.split('\n').slice(1).join('\n');

    // Parse CSV with proper headers
    const records = csv.parse(lines, {
      columns: true,
      skip_empty_lines: true,
      trim: true,
      relax_column_count: true,
      relax_quotes: true,
    });

    console.log(`📊 Parsed ${records.length} total records`);

    // Filter out empty rows, keeping only data rows with valid names
    const dataRows = records.filter(row => {
      if (!row.Name) return false;
      const name = row.Name.trim();
      if (name.length === 0 || name.toLowerCase() === 'name') return false;
      return true;
    });

    console.log(`📊 Found ${dataRows.length} records in CSV\n`);

    // Parse and prepare data
    const membersToInsert = dataRows.map((row, index) => {
      const fullName = (row.Name || '').trim();
      const country = (row.Country || 'Philippines').trim();
      const organization = (row.Organization || '').trim();
      const email = (row['Email Add'] || '').trim();

      // Parse name: "Last, First" or "First Last"
      let firstName = '', lastName = '';
      
      if (fullName.includes(',')) {
        // Format: "Last, First" 
        const parts = fullName.split(',').map(p => p.trim());
        lastName = parts[0];
        firstName = parts.slice(1).join(' ');
      } else if (fullName.includes(' ')) {
        // Format: "First Last" - split on last space
        const lastSpaceIdx = fullName.lastIndexOf(' ');
        firstName = fullName.substring(0, lastSpaceIdx);
        lastName = fullName.substring(lastSpaceIdx + 1);
      } else {
        firstName = fullName;
        lastName = '';
      }

      // Note: member_number will be auto-generated by database trigger

      return {
        first_name: firstName.trim(),
        last_name: lastName.trim(),
        email: email || null,
        country: country || 'Philippines',
        organization: organization || null,
        membership_type: 'regular',
        status: 'active',
        date_admitted: new Date().toISOString().split('T')[0],
        notes: null,
        avatar_url: null,
      };
    });

    console.log(`📝 Importing ${membersToInsert.length} members...\n`);

    // Insert in batches
    const batchSize = 50;
    for (let i = 0; i < membersToInsert.length; i += batchSize) {
      const batch = membersToInsert.slice(i, i + batchSize);
      const { error } = await supabase
        .from('members')
        .insert(batch);

      if (error) {
        console.error(`❌ Batch ${Math.floor(i / batchSize) + 1} failed:`, error);
        process.exit(1);
      }

      console.log(`✅ Batch ${Math.floor(i / batchSize) + 1} imported (${batch.length} members)`);
    }

    const { count } = await supabase
      .from('members')
      .select('*', { count: 'exact', head: true });

    console.log(`\n✨ Successfully imported ${membersToInsert.length} clean members!`);
    console.log(`📊 Total members in system: ${count}`);
    console.log(`� Member numbers: Auto-generated by database (MEM-2026-XXXXX format)`);

  } catch (error) {
    console.error('❌ Import failed:', error);
    process.exit(1);
  }
}

importCSV();
