-- =====================================================
-- ASSET MANAGEMENT SYSTEM
-- Complete schema for tracking company assets
-- =====================================================

-- Drop existing tables and objects if they exist
DROP TRIGGER IF EXISTS trigger_update_asset_on_assignment ON asset_assignments;
DROP TRIGGER IF EXISTS trigger_generate_asset_tag ON assets;
DROP FUNCTION IF EXISTS update_asset_on_assignment();
DROP FUNCTION IF EXISTS generate_asset_tag();
DROP SEQUENCE IF EXISTS asset_tag_seq;

DROP TABLE IF EXISTS asset_requests CASCADE;
DROP TABLE IF EXISTS asset_maintenance CASCADE;
DROP TABLE IF EXISTS asset_assignments CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS asset_vendors CASCADE;
DROP TABLE IF EXISTS asset_brands CASCADE;
DROP TABLE IF EXISTS asset_categories CASCADE;

-- Asset Categories Table (IT Equipment, Furniture, Vehicles, etc.)
CREATE TABLE IF NOT EXISTS asset_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  icon VARCHAR(50), -- For UI display
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asset Brands Table
CREATE TABLE IF NOT EXISTS asset_brands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asset Vendors/Suppliers Table
CREATE TABLE IF NOT EXISTS asset_vendors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  contact_person VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Main Assets Table
CREATE TABLE IF NOT EXISTS assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_tag VARCHAR(50) UNIQUE, -- Unique identifier (e.g., AST-2024-001), auto-generated by trigger
  name VARCHAR(255) NOT NULL,
  category_id UUID REFERENCES asset_categories(id) ON DELETE SET NULL,
  brand_id UUID REFERENCES asset_brands(id) ON DELETE SET NULL,
  model VARCHAR(255),
  serial_number VARCHAR(255),
  
  -- Purchase Information
  vendor_id UUID REFERENCES asset_vendors(id) ON DELETE SET NULL,
  purchase_date DATE,
  purchase_price DECIMAL(12, 2),
  purchase_order_number VARCHAR(100),
  
  -- Warranty Information
  warranty_start_date DATE,
  warranty_end_date DATE,
  warranty_details TEXT,
  
  -- Depreciation
  useful_life_years INTEGER,
  salvage_value DECIMAL(12, 2),
  depreciation_method VARCHAR(50) CHECK (depreciation_method IN ('straight_line', 'declining_balance', 'none')),
  
  -- Status and Condition
  status VARCHAR(50) DEFAULT 'available' CHECK (status IN ('available', 'assigned', 'maintenance', 'retired', 'lost', 'damaged')),
  condition VARCHAR(50) CHECK (condition IN ('excellent', 'good', 'fair', 'poor')),
  
  -- Location and Assignment
  location VARCHAR(255),
  assigned_to UUID REFERENCES employees(id) ON DELETE SET NULL,
  assigned_date DATE,
  
  -- Additional Details
  specifications JSONB, -- Store detailed specs (RAM, Storage, etc.)
  qr_code TEXT,
  image_url TEXT,
  notes TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asset Assignment History
CREATE TABLE IF NOT EXISTS asset_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id UUID NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  assigned_by UUID REFERENCES employees(id) ON DELETE SET NULL,
  assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,
  returned_date DATE,
  returned_by UUID REFERENCES employees(id) ON DELETE SET NULL,
  condition_on_assignment VARCHAR(50),
  condition_on_return VARCHAR(50),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asset Maintenance Records
CREATE TABLE IF NOT EXISTS asset_maintenance (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id UUID NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  maintenance_type VARCHAR(50) CHECK (maintenance_type IN ('repair', 'inspection', 'upgrade', 'cleaning', 'calibration')),
  scheduled_date DATE,
  completed_date DATE,
  performed_by VARCHAR(255),
  vendor_id UUID REFERENCES asset_vendors(id) ON DELETE SET NULL,
  cost DECIMAL(10, 2),
  description TEXT NOT NULL,
  notes TEXT,
  status VARCHAR(50) DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asset Requests (Employees requesting equipment)
CREATE TABLE IF NOT EXISTS asset_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  category_id UUID REFERENCES asset_categories(id) ON DELETE SET NULL,
  item_description TEXT NOT NULL,
  justification TEXT,
  priority VARCHAR(50) DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'fulfilled')),
  requested_date DATE DEFAULT CURRENT_DATE,
  approved_by UUID REFERENCES employees(id) ON DELETE SET NULL,
  approved_date DATE,
  fulfilled_date DATE,
  assigned_asset_id UUID REFERENCES assets(id) ON DELETE SET NULL,
  rejection_reason TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Indexes
CREATE INDEX IF NOT EXISTS idx_assets_asset_tag ON assets(asset_tag);
CREATE INDEX IF NOT EXISTS idx_assets_category ON assets(category_id);
CREATE INDEX IF NOT EXISTS idx_assets_brand ON assets(brand_id);
CREATE INDEX IF NOT EXISTS idx_assets_vendor ON assets(vendor_id);
CREATE INDEX IF NOT EXISTS idx_assets_status ON assets(status);
CREATE INDEX IF NOT EXISTS idx_assets_assigned_to ON assets(assigned_to);
CREATE INDEX IF NOT EXISTS idx_asset_assignments_asset ON asset_assignments(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_assignments_employee ON asset_assignments(employee_id);
CREATE INDEX IF NOT EXISTS idx_asset_maintenance_asset ON asset_maintenance(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_maintenance_status ON asset_maintenance(status);
CREATE INDEX IF NOT EXISTS idx_asset_requests_employee ON asset_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_asset_requests_status ON asset_requests(status);

-- Enable Row Level Security
ALTER TABLE asset_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_maintenance ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_requests ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Asset Categories
CREATE POLICY "Anyone can view asset categories"
  ON asset_categories FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage asset categories"
  ON asset_categories FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr')
    )
  );

-- RLS Policies for Asset Brands
CREATE POLICY "Anyone can view asset brands"
  ON asset_brands FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage asset brands"
  ON asset_brands FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr')
    )
  );

-- RLS Policies for Asset Vendors
CREATE POLICY "Anyone can view asset vendors"
  ON asset_vendors FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage asset vendors"
  ON asset_vendors FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr')
    )
  );

-- RLS Policies for Assets
CREATE POLICY "Anyone can view assets"
  ON assets FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage assets"
  ON assets FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr')
    )
  );

-- RLS Policies for Asset Assignments
CREATE POLICY "Anyone can view asset assignments"
  ON asset_assignments FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage asset assignments"
  ON asset_assignments FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr')
    )
  );

-- RLS Policies for Asset Maintenance
CREATE POLICY "Anyone can view asset maintenance"
  ON asset_maintenance FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can manage asset maintenance"
  ON asset_maintenance FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr')
    )
  );

-- RLS Policies for Asset Requests
CREATE POLICY "Employees can view their own requests"
  ON asset_requests FOR SELECT
  TO authenticated
  USING (
    employee_id IN (
      SELECT employee_id FROM user_roles WHERE user_id = auth.uid()
    )
    OR
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr', 'manager')
    )
  );

CREATE POLICY "Employees can create their own requests"
  ON asset_requests FOR INSERT
  TO authenticated
  WITH CHECK (
    employee_id IN (
      SELECT employee_id FROM user_roles WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can manage all asset requests"
  ON asset_requests FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_id = auth.uid() AND role IN ('admin', 'hr')
    )
  );

-- Insert Default Asset Categories
INSERT INTO asset_categories (name, description, icon) VALUES
  ('IT Equipment', 'Computers, laptops, monitors, and peripherals', 'Laptop'),
  ('Office Furniture', 'Desks, chairs, cabinets, and storage', 'Armchair'),
  ('Vehicles', 'Company cars, motorcycles, and transport', 'Car'),
  ('Tools & Machinery', 'Specialized tools and equipment', 'Wrench'),
  ('Electronics', 'Phones, tablets, cameras, and devices', 'Smartphone'),
  ('Other Assets', 'Miscellaneous company property', 'Package')
ON CONFLICT (name) DO NOTHING;

-- Create sequence for asset tags
CREATE SEQUENCE IF NOT EXISTS asset_tag_seq START 1;

-- Function to auto-generate asset tags
CREATE OR REPLACE FUNCTION generate_asset_tag()
RETURNS TRIGGER AS $$
DECLARE
  next_number INTEGER;
  new_tag VARCHAR(50);
BEGIN
  -- Always generate if not provided or empty
  IF NEW.asset_tag IS NULL OR TRIM(NEW.asset_tag) = '' THEN
    -- Get next number from sequence
    next_number := nextval('asset_tag_seq');
    
    -- Generate new tag: AST-00001
    NEW.asset_tag := 'AST-' || LPAD(next_number::TEXT, 5, '0');
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-generate asset tags
DROP TRIGGER IF EXISTS trigger_generate_asset_tag ON assets;
CREATE TRIGGER trigger_generate_asset_tag
  BEFORE INSERT ON assets
  FOR EACH ROW
  EXECUTE FUNCTION generate_asset_tag();

-- Function to update asset status when assigned/returned
CREATE OR REPLACE FUNCTION update_asset_on_assignment()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- Update asset status to assigned
    UPDATE assets
    SET 
      status = 'assigned',
      assigned_to = NEW.employee_id,
      assigned_date = NEW.assigned_date,
      updated_at = NOW()
    WHERE id = NEW.asset_id;
  ELSIF TG_OP = 'UPDATE' AND NEW.returned_date IS NOT NULL AND OLD.returned_date IS NULL THEN
    -- Update asset status to available when returned
    UPDATE assets
    SET 
      status = 'available',
      assigned_to = NULL,
      assigned_date = NULL,
      updated_at = NOW()
    WHERE id = NEW.asset_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update asset status on assignment changes
DROP TRIGGER IF EXISTS trigger_update_asset_on_assignment ON asset_assignments;
CREATE TRIGGER trigger_update_asset_on_assignment
  AFTER INSERT OR UPDATE ON asset_assignments
  FOR EACH ROW
  EXECUTE FUNCTION update_asset_on_assignment();
